#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate main/secrets.h from root config.json.

Keeps secrets in a single place without duplicating them across repos.
Never prints secret values to console.
"""
import sys, json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
ROOT = BASE.parent
CONFIG_FILE = ROOT / "config.json"
TARGET_FILE = BASE / "main" / "secrets.h"


def escape_c_str(s: str) -> str:
    """Escape string as C byte string literal (handling multi-byte UTF-8)."""
    res = []
    raw_bytes = s.encode("utf-8")
    for b in raw_bytes:
        if b == ord('\\'):
            res.append('\\\\')
        elif b == ord('"'):
            res.append('\\"')
        elif 32 <= b <= 126:
            res.append(chr(b))
        else:
            res.append('\\%03o' % b)
    return "".join(res)


def main():
    force = "--force" in sys.argv or "-f" in sys.argv

    if not CONFIG_FILE.exists():
        print("[!] config.json not found at %s" % CONFIG_FILE, file=sys.stderr)
        return 1

    if TARGET_FILE.exists() and not force:
        print("[*] %s already exists. Use --force to overwrite." % TARGET_FILE)
        return 0

    try:
        cfg = json.loads(CONFIG_FILE.read_text(encoding="utf-8"))
    except Exception as e:
        print("[!] Error reading config.json: %s" % e, file=sys.stderr)
        return 1

    # Extract configuration
    wifi_ssid = cfg.get("wifi_ssid", "")
    wifi_pass = cfg.get("wifi_password", "")
    petkit_mac = cfg.get("mac", "")
    raw_secret = cfg.get("secret", "").replace(" ", "").replace(":", "")
    # Left-pad secret to 16 hex chars (8 bytes)
    secret_hex = raw_secret.zfill(16)

    tg_token = cfg.get("telegram_token", "")
    tg_chat = str(cfg.get("telegram_chat_id", ""))
    tg_enabled = 1 if cfg.get("telegram_enabled", True) else 0

    poll_min = int(cfg.get("poll_minutes", 5))
    thirst_h = int(cfg.get("thirst_hours", 8))
    thirst_esc_h = int(cfg.get("thirst_escalate_hours", 12))
    normal_gap_min = int(cfg.get("normal_gap_minutes", 416))
    
    report_time = str(cfg.get("report_time", "23:59"))
    if ":" in report_time:
        rh, rm = report_time.split(":", 1)
        report_h, report_m = int(rh), int(rm)
    else:
        report_h, report_m = 23, 59

    report_settle_min = int(cfg.get("report_settle_minutes", 3))
    tz_offset_h = int(float(cfg.get("timezone_offset_hours", 3)))

    content = f"""/* Auto-generated by tools/gen_secrets.py - DO NOT COMMIT */
#ifndef SECRETS_H
#define SECRETS_H

#define WIFI_SSID           "{escape_c_str(wifi_ssid)}"
#define WIFI_PASS           "{escape_c_str(wifi_pass)}"

#define PETKIT_MAC          "{escape_c_str(petkit_mac)}"
#define PETKIT_SECRET_HEX   "{escape_c_str(secret_hex)}"

#define TG_TOKEN            "{escape_c_str(tg_token)}"
#define TG_CHAT_ID          "{escape_c_str(tg_chat)}"
#define TG_ENABLED          {tg_enabled}

#define CONFIG_POLL_MINUTES          {poll_min}
#define CONFIG_THIRST_HOURS          {thirst_h}
#define CONFIG_THIRST_ESCALATE_HOURS {thirst_esc_h}
#define CONFIG_NORMAL_GAP_MINUTES    {normal_gap_min}
#define CONFIG_REPORT_HOUR           {report_h}
#define CONFIG_REPORT_MIN            {report_m}
#define CONFIG_REPORT_SETTLE_MIN     {report_settle_min}
#define CONFIG_TIMEZONE_OFFSET_HOURS {tz_offset_h}

#endif /* SECRETS_H */
"""
    TARGET_FILE.parent.mkdir(parents=True, exist_ok=True)
    TARGET_FILE.write_text(content, encoding="utf-8")
    print("[+] Successfully generated %s from config.json" % TARGET_FILE)
    return 0


if __name__ == "__main__":
    sys.exit(main())
