#!/usr/bin/env python3
"""See what this gateway does, without owning the hardware.

Replays the six-hour capture in data/ through the real core and prints the
messages it produces. No fountain, no phone, no Telegram bot, no config file.

    python tools/demo.py
    python tools/demo.py --html      # exactly what Telegram receives

The only thing you need is the compiled core:

    make -C core        (Linux, macOS)
    core\\build.bat      (Windows)

Everything printed is generated by the same C code that runs on the board. The
timestamps, the visit durations and the battery readings are all real, measured
on the night of 19 August 2026. See data/README.md for the capture format.
"""

import argparse
import calendar
import datetime
import gzip
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import pk                                                    # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
CAPTURE = os.path.join(os.path.dirname(HERE), "data",
                       "baseline-20260819.jsonl.gz")

# The capture was recorded in Turkey, which is permanently UTC+3. This is a
# property of the file, not of whoever is running the demo.
CAPTURE_TZ = 3 * 3600

POLL_SEC = 5 * 60


def unix(stamp):
    dt = datetime.datetime.strptime(stamp, "%Y-%m-%d %H:%M:%S")
    return calendar.timegm(dt.timetuple()) - CAPTURE_TZ


def local(ts):
    return datetime.datetime.fromtimestamp(
        ts + CAPTURE_TZ, datetime.timezone.utc).strftime("%H:%M")


# The capture holds raw detection edges. The fountain itself does not: it merges
# nearby detections into one visit and throws away brief weak touches before it
# writes a history record, and the history is what the gateway actually reads.
# Applying the same rule here is what makes this demo show the real product
# rather than the sensor. The thresholds are the measured ones, see
# docs/protocol.md under "The fountain merges nearby detections".
MERGE_GAP_SEC = 30
MIN_VISIT_SEC = 30


def merge(raw):
    """Raw detection edges -> the visits the fountain would have recorded."""
    out = []
    for start, dur in sorted(raw):
        end = start + dur
        if out and start - out[-1][1] <= MERGE_GAP_SEC:
            out[-1][1] = max(out[-1][1], end)
        else:
            out.append([start, end])
    return [(s, e - s) for s, e in out if e - s >= MIN_VISIT_SEC]


def plain(html):
    """Render Telegram HTML as something readable in a terminal."""
    t = html
    t = re.sub(r"<blockquote[^>]*>", "\n│ ", t)
    t = t.replace("</blockquote>", "")
    t = re.sub(r"</?(b|i|code)>", "", t)
    t = t.replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&")
    lines = []
    quoting = False
    for line in t.split("\n"):
        if line.startswith("│ "):
            quoting = True
            lines.append(line)
        elif quoting and line.strip():
            lines.append("│ " + line)
        else:
            if not line.strip():
                quoting = False
            lines.append(line)
    return "\n".join(lines).strip()


def load():
    states, visits = [], []
    starts = []
    with gzip.open(CAPTURE, "rt", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            k = r.get("type")
            if k == "state":
                states.append((unix(r["ts"]), bytes.fromhex(r["hex"])))
            elif k == "visit_start":
                starts.append(unix(r["ts"]))
            elif k == "visit_end":
                end = unix(r["ts"])
                dur = int(r.get("duration_s", 0))
                start = starts.pop(0) if starts else end - dur
                visits.append((start, dur))
    states.sort()
    visits.sort()
    return states, visits


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--html", action="store_true",
                    help="print the raw HTML Telegram receives")
    args = ap.parse_args()

    if not os.path.exists(CAPTURE):
        sys.exit("capture not found: %s" % CAPTURE)

    states, raw = load()
    if not states:
        sys.exit("no state records in the capture")
    visits = merge(raw)

    print("Replaying %d state pushes from %s"
          % (len(states), os.path.basename(CAPTURE)))
    print("Recorded %s to %s local time, polled every %d minutes."
          % (local(states[0][0]), local(states[-1][0]), POLL_SEC // 60))
    print("%d raw detection edges merge into %d visits, the way the fountain "
          "does it.\n" % (len(raw), len(visits)))

    cfg = pk.default_cfg()
    cfg.tz_offset_sec = CAPTURE_TZ
    cfg.poll_sec = POLL_SEC

    core = pk.Core(cfg, states[0][0])
    shown = 0

    # Subsample to one poll every POLL_SEC, which is what the gateway does. The
    # fountain pushes state far more often than that while connected.
    next_poll = states[0][0]
    for ts, payload in states:
        if ts < next_poll:
            continue
        next_poll = ts + POLL_SEC

        state = pk.state_decode(payload)
        known = [v for v in visits if v[0] <= ts]
        core.poll_ok(state, known, ts)

        for m in core.take():
            shown += 1
            print("=" * 62)
            print("%s   message %d" % (local(ts), shown))
            print("=" * 62)
            print(m if args.html else plain(m))
            print()

    # The capture is six hours long, so no day boundary falls inside it. Ask for
    # the summary directly, which is what the gateway would send after midnight.
    core.report(states[-1][0])
    for m in core.take():
        shown += 1
        print("=" * 62)
        print("daily summary, as it would arrive after midnight")
        print("=" * 62)
        print(m if args.html else plain(m))
        print()

    print("%d message(s) for six hours of monitoring." % shown)
    print("Only the summary: the fountain was healthy and the cat drank, so")
    print("there was nothing to report. Silence is the design, not a bug.")
    print()
    print("Worth checking: the PetKit app's own history screen showed five")
    print("visits for this night, and the merge rule above reproduces all")
    print("five, with the same longest gap of 3 hr 40 min that the README")
    print("quotes. Nothing here is hand-fitted to make the demo look good.")


if __name__ == "__main__":
    main()
